### ISSUE TITLE
 add the source portal to the search result dataset summary

### ISSUE THREAD

**Issue by tobybellwood** [TerriaJS/magda-web#16]
This will be a (maybe) temporary thing until we get a dataset detail page, but it'd be good to reference the source of the dataset (with a nice textual description) in the search results, before the expansion:
(cue bodgy mockup)
![image](https://cloud.githubusercontent.com/assets/4373945/22965404/8a1fcb20-f3b1-11e6-8811-ed84ab4aec1f.png)

as an extension activity, would clicking on the source name perform a MAGDA search on all datasets from that connector?

**Comment by kring** [comment]
Fixed by 95f925c6abc3ad5dea30c6c3f2b20dd73318541e.

**Comment by kring** [comment]
@chloe just pointed out that it was already on the expanded dataset summary, if you didn't know;
![image](https://cloud.githubusercontent.com/assets/924374/23192109/a86ff890-f8f5-11e6-9ef1-bdc813f78032.png)

**Comment by tobybellwood** [comment]
haha - we knew it was there after the expansion, but we just wanted it before!!
