### ISSUE TITLE
Number of hits don't seem to add up right when some don't have publisher info 

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/magda-web#8]
There seem to be some datasets without publishers.  Maybe this is a problem in itself but I'm assuming that it is valid to have this.  If this is not valid, this issue can be closed and I'll create a different one.

When there are some datasets without a publisher in the search returns, the numbers under the publishers list doesn't add up to the same number as the number of results.  This seems to happen reasonably commonly.  Perhaps there should be an "Unspecified" value for publisher so that this isn't confusing for the user and so that they don't think the system is unreliable.

**Comment by chloeleichen** [comment]
We can potentially make the publisher 'Unspecified', then in the facet we should have an 'unspecified' with a `hitCount` as well, this info should probably come from the server since at any time the front end doesn't have information of all the results. @AlexGilleran any thoughts on this? cc @cam-grant

**Comment by chloeleichen** [comment]
Going to display non-existent publisher as `unspecified` for now,  we probably still want to display it in the facet as well.

**Comment by AlexGilleran** [comment]
Yeah I can make an unspecified facet.

**Comment by AlexGilleran** [comment]
I've added "Unspecified" for datasets with a format or publisher that isn't specified... sure makes it obvious how much metadata is missing though :|
